### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [Bkucera/cypress-plugin-tab#61]
Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by DrewMcArthur** [comment]
want to mention that since updating cypress to v10.3.0, i'm getting ` TS2339: Property 'tab' does not exist on type 'Chainable<JQuery<HTMLElement>>'.` errors.  likely related to this.  thanks for your work on this plugin!!

**Comment by sven5** [comment]
No updates since May on this issue?
Is this project considered dead?

**Comment by mryellow** [comment]
Making all these plugins and then failing to do basic maintenance leaves a bad taste. 

I've had to use a fork of every plugin so far as no one is maintaining things or merging PRs.

**Comment by vamcs** [comment]
The latest merge PR should fix the TS error (or at least make it possible to include the types in TSConfig). @kuceb Please, could you make a new release?

**Comment by pointhalo** [comment]
First of all, I would like to thank you for all the time and hard work you put into this plugin.

I am upgrading from cypress 9 to cypress 12 and currently facing the same problem, cypress-plugin-tab is not working after upgrade.
![image](https://github.com/kuceb/cypress-plugin-tab/assets/88709023/6aec1ba4-654a-4a16-8677-0a81785a716d)

We also considered `cypress-real-event`, but compared to cypress-plugin-tab, it cannot provide the test function of key combination, for example, I press tab + shift at the same time.

Wondering if the author still plans to maintain and update the plugin in the future?

**Comment by kuceb** [comment]
Hi, Cypress 10+ Support is in https://github.com/kuceb/cypress-plugin-tab/pull/65
